name: Build bootloader

on: [push, pull_request]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up MinGW
  			  uses: egor-tensin/setup-mingw@v2
  			  	  with:
    			  platform: x64

            - name: Build bootloader
              run: make

            - name: Upload bootloader
              uses: actions/upload-artifact@v3
              with:
                  name: bootloader
                  path: Binaries/BOOTX64.efi
