name: Build the OS
   
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install Nasm
      run: sudo apt-get install nasm
  
    - name: Compile
      run: make # Make this work because rn linking wont work on linux

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Kittnus Root
        path: Binaries/
